<a href="https://colab.research.google.com/github/mkirby1995/DS-Unit-4-Sprint-2-Neural-Networks/blob/master/Assignments/LS_DS_431_Intro_to_NN_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Intro to Neural Networks Assignment

## Define the Following:
You can add image, diagrams, whatever you need to ensure that you understand the concepts below.

### Input Layer: The visable layer of a network that interacts directly with the feed data
### Hidden Layer: Layers after the input layer that cannot be accessed except through the input layer
### Output Layer: The final layer that outputs a vector of answers
### Neuron: A representation of a transformation to the previous layers value
### Weight: The scalar value assigned to an input value in a layer
### Activation Function: A function for transforming the output of a neuron
### Node Map: A visual representation of the structure of a neural netwoks layers
### Perceptron: A neural network with a single layer 


## Inputs -> Outputs

### Explain the flow of information through a neural network from inputs to outputs. Be sure to include: inputs, weights, bias, and activation functions. How does it all flow from beginning to end?

#### The data is fed into an input node where it is then transformed by computing the dot product between the inputs and the weights, this is then combined with a bias value and the result is fed theough am activation function. The process repeats for each node in the network

## Write your own perceptron code that can correctly classify a NAND gate. 

| x1 | x2 | y |
|----|----|---|
| 0  | 0  | 1 |
| 1  | 0  | 1 |
| 0  | 1  | 1 |
| 1  | 1  | 0 |

In [0]:
import numpy as np

np.random.seed(42)

inputs = np.array([
    [0,0,1],
    [1,0,1],
    [0,1,1],
    [1,1,0]
])

correct_outputs = [[0], [1], [1], [0]]

weights = 2 * np.random.random((3, 1)) - 1

In [0]:
def sigmoid(x):
  return 1 / (1 + np.exp(-x))

def sigmoid_derivative(x):
  sx = sigmoid(x)
  return sx * (1-sx)

In [16]:
for iteration in range(100):
  
  weighted_sum = np.dot(inputs, weights)
  
  activated_output = sigmoid(weighted_sum)
  
  error = correct_outputs - activated_output
  
  adjustments = error * sigmoid_derivative(activated_output)
  
  weights += np.dot(inputs.T, adjustments)
  
print(weights, '\n\n', activated_output)

[[-0.36057752]
 [-0.36057752]
 [ 0.96623867]] 

 [[0.72436915]
 [0.64695042]
 [0.64695042]
 [0.32713869]]


## Implement your own Perceptron Class and use it to classify a binary dataset like: 
- [The Pima Indians Diabetes dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/diabetes.csv) 
- [Titanic](https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv)
- [A two-class version of the Iris dataset](https://raw.githubusercontent.com/ryanleeallred/datasets/master/Iris.csv)

You may need to search for other's implementations in order to get inspiration for your own. There are *lots* of perceptron implementations on the internet with varying levels of sophistication and complexity. Whatever your approach, make sure you understand **every** line of your implementation and what its purpose is.

In [19]:
import pandas as pd
csv = 'https://raw.githubusercontent.com/ryanleeallred/datasets/master/titanic.csv'
df = pd.read_csv(csv)
df.head()

Unnamed: 0  survived  pclass     sex  ...  deck  embark_town  alive  alone
0           0         0       3    male  ...   NaN  Southampton     no  False
1           1         1       1  female  ...     C    Cherbourg    yes  False
2           2         1       3  female  ...   NaN  Southampton    yes   True
3           3         1       1  female  ...     C  Southampton    yes  False
4           4         0       3    male  ...   NaN  Southampton     no   True

[5 rows x 16 columns]

In [0]:
df['sex'] = df['sex'].replace({'male':1, 'female':0})

In [0]:
X = df[['pclass', 'sex']].values
y = np.array(df['survived'].replace({0:-1}))

In [38]:
X

array([[3, 1],
       [1, 0],
       [3, 0],
       ...,
       [3, 0],
       [1, 1],
       [3, 1]])

In [39]:
y

array([-1,  1,  1,  1, -1, -1, -1, -1,  1,  1,  1,  1, -1, -1, -1,  1, -1,
        1, -1,  1, -1,  1,  1,  1, -1,  1, -1, -1,  1, -1, -1,  1,  1, -1,
       -1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1, -1, -1,  1, -1, -1, -1,
       -1,  1,  1, -1,  1,  1, -1,  1, -1, -1,  1, -1, -1, -1,  1,  1, -1,
        1, -1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1, -1,  1,  1, -1,  1,
        1, -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1, -1, -1,
       -1, -1, -1, -1,  1,  1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1,  1, -1,  1, -1,  1,  1, -1, -1, -1, -1,  1, -1, -1,
        1, -1, -1, -1, -1,  1,  1, -1, -1, -1,  1, -1, -1, -1, -1,  1, -1,
       -1, -1, -1,  1, -1, -1, -1, -1,  1, -1, -1, -1,  1,  1, -1, -1, -1,
       -1, -1,  1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,  1, -1,  1,
        1, -1, -1,  1, -1,  1,  1,  1,  1, -1, -1,  1, -1, -1, -1, -1, -1,
        1, -1, -1,  1,  1,  1, -1,  1, -1, -1, -1,  1,  1, -1,  1, -1,  1,
       -1, -1, -1,  1, -1

In [0]:
class Perceptron(object):
  def __init__(self, rate = .01, n_iter = 10):
    self.rate = rate
    self.n_iter = n_iter
    
  def fit(self, X, y):
    self.weight = np.zeros(1 + X.shape[1])
    self.errors = []
    
    for i in range(self.n_iter):
      error = 0
      for xi, target in zip(X, y):
        delta_w = self.rate * (target - self.predict(xi))
        self.weight[1:] += delta_w * xi
        self.weight[0] += delta_w
        error += int(delta_w != 0.0)
      self.errors.append(error)
    return self
  
  def net_input(self, X):
    return np.dot(X, self.weight[1:]) + self.weight[0]
  
  def predict(self, X):
    return np.where(self.net_input(X) >= 0.0, 1, -1)

In [41]:
model = Perceptron()

model.fit(X, y)

In [45]:
model.predict([[3, 1]])

array([-1])

## Stretch Goals:

- Research "backpropagation" to learn how weights get updated in neural networks (tomorrow's lecture). 
- Implement a multi-layer perceptron. (for non-linearly separable classes)
- Try and implement your own backpropagation algorithm.
- What are the pros and cons of the different activation functions? How should you decide between them for the different layers of a neural network?